### ISSUE TITLE
Script stopped working?

### ISSUE THREAD

**Issue by darkdroider** [Nuklon/Steam-Economy-Enhancer#165]
Script stopped working

**Comment by naqaden** [comment]
It looks like a Steam-side problem. I just listed a card for sale with the script. Market history confirms it, but my market listings won't load. My mobile app isn't connecting properly either.

**Comment by darkdroider** [comment]
> It looks like a Steam-side problem. I just listed a card for sale with the script. Market history confirms it, but my market listings won't load. My mobile app isn't connecting properly either.

thanks

**Comment by darkdroider** [comment]
![Captura de tela 2022-10-27 210347](https://user-images.githubusercontent.com/64504631/198419714-17bf306e-8412-424c-b527-a1eca68e6276.png)

**Comment by leftbones** [comment]
Steam market/inventory/trade servers have been a mess for a couple of weeks now, I'm willing to bet that's the issue. I'm also unable to list anything, it just says "processing" forever.

**Comment by Tomy91218** [comment]
> Steam market/inventory/trade servers have been a mess for a couple of weeks now, I'm willing to bet that's the issue. I'm also unable to list anything, it just says "processing" forever.

Yes, that is probably the problem, it does not allow me to sell anything, nor re-publish the overpriced

**Comment by rts7** [comment]
It looks like steam decided to lower the amount of requests per minute so using it gets you ip banned from the market. Since the owner is probably away, can someone understand and tell us what do we need to edit to increase the delay between each request?

**Comment by Citrinate** [comment]
There's now a very restrictive rate limit on `https://steamcommunity.com/market/itemordershistogram`

This "new" rate limit doesn't feel intentional.  I'm only able to get ~10 requests an hour, in which case there's really nothing you can do to avoid hitting it.  This is low enough to break even the lightest market usage, as Steam itself calls this every 5 seconds while browsing any market listing page.  Though for how completely this breaks the market, I'm seeing surprisingly little discussion about it elsewhere.

**Comment by leftbones** [comment]
Considering how infrequently someone should need to list a large amount of cards or something, the script could just be ran overnight. If nobody makes a PR to increase the delay, I’ll give it a go later.

**Comment by darkdroider** [comment]
> 

thanks guys for response...Hey man big fan here.

**Comment by RDru** [comment]
There is actually no need for histogram when you are using average history price. I have removed some returns/callbacks on histogram fail and added some if(histogram != null) where histogram was used and it works.

**Comment by woctezuma** [comment]
So that is why every page on the Steam Market looks like this.

![Market](https://i.imgur.com/2w144Db.png)

**Comment by pepzwee** [comment]
> I'm only able to get ~10 requests an hour, in which case there's really nothing you can do to avoid hitting it. 

From my testing that endpoint is actually more like 10 requests every 2 hours. In my testing I stopped getting 429 errors once I reached 12-13 minute cooldown after each request.

**Comment by leftbones** [comment]
> There is actually no need for histogram when you are using average history price. I have removed some returns/callbacks on histogram fail and added some if(histogram != null) where histogram was used and it works.

If you have it working again, please make a pull request!

**Comment by pacopepepipo** [comment]
> There is actually no need for histogram when you are using average history price. I have removed some returns/callbacks on histogram fail and added some if(histogram != null) where histogram was used and it works.

would you mind to share?

**Comment by darkdroider** [comment]
sorry guys, i dont speak English, and I know a little about programming, but is it related to a server error?
You have this error from this Tuesday, which is Steam server maintenance day.
[https://steamstat.us/](url)


![Captura de tela 2022-10-31 040459](https://user-images.githubusercontent.com/64504631/198950656-80c20685-c673-4cbd-8462-753b81a6c570.png)

**Comment by darkdroider** [comment]
Whats WS?

**Comment by GwynbleiddI** [comment]
Good day to you all! Share at least some working version of

**Comment by darkdroider** [comment]
> Good day to you all! Share at least some working version o

**Comment by GwynbleiddI** [comment]
Good day to you all! Share at least some working version of the script

**Comment by kasumijaponesa** [comment]
> Good day to you all! Share at least some working version of the script

yes, please guys

**Comment by Nuklon** [comment]
Can confirm, it indeed seems the very low rate limit. I don't have a lot of time to look into this right now so a PR is welcome.

**Comment by darkdroider** [comment]
Augmented Steam price inquiry requests do not go over the same limitation as Stem Economy Enhancer
![Screenshot_20221031-0811452](https://user-images.githubusercontent.com/64504631/198995471-36009a5d-e71d-4ad9-b338-31294b402d62.png)

**Comment by darkdroider** [comment]
Augmented Steam price inquiry requests do not go over the same limitation as Stem Economy Enhancer
![Captura de tela 2022-10-31 081508](https://user-images.githubusercontent.com/64504631/198995713-6e93c663-86b4-47ac-80dc-7d8312e63f51.png)

**Comment by woctezuma** [comment]
It is possible that the issue was fixed by Valve. I don't encounter the error `429 Too Many Requests` anymore.

**Comment by rts7** [comment]
I still get it after 10 requests even if I am just on my inventory with a fresh ip. Did you change anything else?

As for Augmented Steam, considering the price is different in the screenshot provided, it probably uses the lowest price which doesn't need the histogram but is less useful. I am guessing what RDru did uses the same stat.

**Comment by Nuklon** [comment]
Same, 10 requests max it seems.

**Comment by woctezuma** [comment]
> I still get it after 10 requests even if I am just on my inventory with a fresh ip. Did you change anything else?

Do you get the error `429` when you idle on this page?
https://steamcommunity.com/market/listings/753/753-Sack%20of%20Gems

**Comment by Nuklon** [comment]
Yes, 429 (Too Many Requests).

**Comment by rts7** [comment]
After being banned I get the error. If I am not banned yet I can open as many tabs I want without problems. What is the difference between actually opening the webpage and have it make the request for you and making the request yourself independently? The first is fine, the second gets you banned.

**Comment by Nuklon** [comment]
I see country=XX now being added on store page requests, it seems that's necessary now to avoid 429s. It's working for me again, I'll upload a fix.

**Comment by woctezuma** [comment]
I don't think the `country` parameter explains everything, because I was experiencing the issue in my browser earlier:
- https://github.com/Nuklon/Steam-Economy-Enhancer/issues/165#issuecomment-1296193340

So the issue was solved by Valve fixing their mistakenly strict rate-limits.

However, it is possible that the `country` parameter is now necessary if you send your GET requests through other means.

**Comment by leftbones** [comment]
I'm still having this problem even after updating. I looked at the console and even before I press any buttons, just after loading the page, I'm getting continuous messages saying "too many requests", and the same happens after trying to sell all cards.

**Comment by woctezuma** [comment]
> 8 hours later, tried again and it's working now. Maybe a Steam server issue. Thanks for the fix!

I think the rate-limits are different than before. So if you use some home-made scripts which check `itemordershistogram` many times, you can receive error `429`. Not sure if this can happen if you use this script.

**Comment by woctezuma** [comment]
Actually, it happens again to me, even without home-made scripts.

**Comment by Nuklon** [comment]
Still works fine for me, it has no trouble retreiving 250+ listings. Are you using other scripts/addons on Steam?

**Comment by GwynbleiddI** [comment]
Yesterday sold over 11k cards and 8k 
PayDay2 Flight was normal

**Comment by woctezuma** [comment]
> Still works fine for me, it has no trouble retrieving 250+ listings. Are you using other scripts/addons on Steam?

Not today, but I ran a script yesterday. I suspect I have reached a daily rate-limit. I will try again without any other script tomorrow.

**Comment by pacopepepipo** [comment]
can confirm is working again

> I see country=XX now being added on store page requests, it seems that's necessary now to avoid 429s. It's working for me again, I'll upload a fix.

can I ask what do that? tell the country we are by ip? the currency?

**Comment by woctezuma** [comment]
> can I ask what do that? tell the country we are by ip? the currency?

This is not for you. This was added to the code of the script in this Github repository.

**Comment by Citrinate** [comment]
Script seems to be fine now.

For anyone using `market/itemordershistogram` in other projects, the ~10 requests per 2 hours rate limit still exists under certain conditions.  From my testing, you'll get a `429` error if you use the `norender=1` query parameter, or if you don't send a `sessionid` cookie.

**Comment by woctezuma** [comment]
> Edit: There might be further requirements to avoid the error

Very interesting. Please keep us posted if you find more requirements.

**Comment by Citrinate** [comment]
> before this change I could put the 2 accounts to list all items at the same time. If I do that now, I encounter the error and get banned again in seconds. If I use one, for now it seems to be working.

I couldn't duplicate any issues with using multiple accounts at the same time.  Tested by sitting on [this page](https://steamcommunity.com/market/listings/753/753-Sack%20of%20Gems) in the browser with 3 different accounts at once.  Haven't tested actually using the script with multiple accounts yet though.

> In my case, I hit the `429` error very fast (~10 requests as you mentioned) with [`GET /market/itemordershistogram`](https://github.com/Revadike/InternalSteamWebAPI/wiki/Get-Market-Item-Orders-Histogram) despite:
> 
> * not explicitly setting `norender=1`,
> * sending a `sessionid` cookie.

Same.

Tried narrowing down which headers are required by removing them one at a time (except for `Cookie`) and sending 10 requests.  With only `Cookie` and `Accept: */*` set, I was able to make 10 requests.  The first request I made without `Accept` got the `429` error.  Can't test anymore past that for another 2 hours.

**Comment by woctezuma** [comment]
I hit the limit even using the browser only. I have opened a few market pages and that is it.

**Comment by Nuklon** [comment]
Still works fine for me. I don't use any other extensions on Steam.

**Comment by woctezuma** [comment]
I don't think this is due to an add-on. I will try again later in private mode.

Basically, opening 10 pages should trigger the rate-limit. For instance, these are the 15 trading cards for Dead Cells.
If you click on each page, I suspect that you should trigger it (and get "banned" for 2 hours according to Citrinate).
1. https://steamcommunity.com/market/listings/753/588650-%20THE%20QUICK%20BOW
1. https://steamcommunity.com/market/listings/753/588650-BITER%20SWARM
1. https://steamcommunity.com/market/listings/753/588650-CROW%27S%20WINGS
1. https://steamcommunity.com/market/listings/753/588650-FIRE%20BRANDS
1. https://steamcommunity.com/market/listings/753/588650-FROST%20BLAST
1. https://steamcommunity.com/market/listings/753/588650-THE%20ASSAULT%20SHIELD
1. https://steamcommunity.com/market/listings/753/588650-THE%20BROAD%20SWORD
1. https://steamcommunity.com/market/listings/753/588650-THE%20CURSED%20SWORD
1. https://steamcommunity.com/market/listings/753/588650-THE%20FIRE%20BOMB
1. https://steamcommunity.com/market/listings/753/588650-THE%20GREED%20SHIELD
1. https://steamcommunity.com/market/listings/753/588650-THE%20NUTCRACKER
1. https://steamcommunity.com/market/listings/753/588650-THE%20SCAVENGER%20SWORD
1. https://steamcommunity.com/market/listings/753/588650-THE%20SWIFT%20SWORD
1. https://steamcommunity.com/market/listings/753/588650-THE%20TWIN%20DAGGERS
1. https://steamcommunity.com/market/listings/753/588650-THE%20WAR%20SPEAR

Don't do it. 😉

**Comment by Nuklon** [comment]
That works for me also, no bans.

**Comment by woctezuma** [comment]
Okay, it looks like it was an issue on my side. I was using the wrong `sessionid` in my cookie.
