### ISSUE TITLE
Fix getCurrentMarketItemNameId error

### ISSUE THREAD

**Issue by disanyixing** [Nuklon/Steam-Economy-Enhancer#186]
![image](https://github.com/Nuklon/Steam-Economy-Enhancer/assets/72839560/994b12f4-8bd1-40ab-a1d0-79be11f37e46)

![image](https://github.com/Nuklon/Steam-Economy-Enhancer/assets/72839560/3a0b1c2b-6279-4501-a27c-fb9ed8f35c48)
```
var matches = /Market_LoadOrderSpread\( (.+) \);/.exec(page);
var item_nameid = matches[1];
```
This will result in two values：
The first value comes from Market_LoadOrderSpread( 77489411 ); // The matches[1] is 77489411
The second value comes from Market_LoadOrderSpread( 77489411 ); }, 2 * 60 * 1000 ); // The matches[1] is 77489411 ); }, 2 * 60 * 1000 
![image](https://github.com/Nuklon/Steam-Economy-Enhancer/assets/72839560/5fc73a0f-9ce0-4aa0-9755-55236e98aa66)
The second value will cause the value of the red box to become 77489411 ); }, 2 * 60 * 1000 

![image](https://github.com/Nuklon/Steam-Economy-Enhancer/assets/72839560/5ac62dba-e4e6-4b22-a63a-5b63da6dbabe)
After fixing the regular expression：
Both values come from Market_LoadOrderSpread( 77489411 ); // Both matches[1] are 77489411

**Comment by xPaw** [comment]
This was fixed by https://github.com/Nuklon/Steam-Economy-Enhancer/commit/1fcd98affbb2b31a4b370cab103b051e5d8b38e5 i think

**Comment by disanyixing** [comment]
> This was fixed by [1fcd98a](https://github.com/Nuklon/Steam-Economy-Enhancer/commit/1fcd98affbb2b31a4b370cab103b051e5d8b38e5) i think

Yes. But this issue opened on Sep 30, 2023. Before that time this issue had not fixed.

**Comment by xPaw** [comment]
Well you can close the issue then.
