### ISSUE TITLE
Max price used when no recent sales

### ISSUE THREAD

**Issue by Omicron666** [Nuklon/Steam-Economy-Enhancer#9]
When using "Sell all cards" the script is selling items at their max price instead of what it normally use, if respective cards have no recent sale.

And it doesn't matter which price strategy we choose. (lowest price or max(lowest_price, last_12h_average_price))

**Comment by Nuklon** [comment]
There was an issue with 3.2.0, this is fixed in 3.2.5, please update the script (force).

**Comment by Omicron666** [comment]
Well, I still get some bugged items http://i.imgur.com/3yDe6G2.png
Info on the given item : http://i.imgur.com/ZKf873K.png
